# Generated by Django 6.0 on 2025-12-23 02:03

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.generate_room_code, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('predicting', 'Prediciendo'), ('locked', 'Bloqueado'), ('results', 'Resultados')], default='predicting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.room')),
            ],
            options={
                'unique_together': {('room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_as_giver', to='core.participant')),
                ('predicted_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_as_receiver', to='core.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_made', to='core.participant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.room')),
            ],
            options={
                'unique_together': {('user', 'predicted_receiver')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_to', to='core.participant')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_from', to='core.participant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.room')),
            ],
            options={
                'unique_together': {('room', 'giver')},
            },
        ),
    ]
